[package]
name = "bankstream"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = "4.5.20"
csv = "1.3.0"
log = "0.4.22"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6.0"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
